# -*- coding: utf-8 -*-
"""Shared model configuration."""

from __future__ import annotations


DEFAULT_CHAT_MODEL = "qwen3-max"

ROUTER_MODEL = DEFAULT_CHAT_MODEL
PLANNER_MODEL = DEFAULT_CHAT_MODEL
SQL_MODEL = DEFAULT_CHAT_MODEL
RAG_QUERY_MODEL = DEFAULT_CHAT_MODEL
RAG_SUMMARY_MODEL = DEFAULT_CHAT_MODEL
ANALYSIS_MODEL = DEFAULT_CHAT_MODEL

DEFAULT_TEMPERATURE = 0.2
DEFAULT_MAX_TOKENS = 2000
DEFAULT_TOP_P = 0.9

ROUTER_TEMPERATURE = 0.0
ROUTER_MAX_TOKENS = 800
ROUTER_TOP_P = 0.9

PLANNER_TEMPERATURE = 0.0
PLANNER_MAX_TOKENS = 600
PLANNER_TOP_P = 0.9

SQL_TEMPERATURE = 0.0
SQL_MAX_TOKENS = 1200
SQL_TOP_P = 0.9

RAG_QUERY_TEMPERATURE = 0.0
RAG_QUERY_MAX_TOKENS = 800
RAG_QUERY_TOP_P = 0.9

RAG_SUMMARY_TEMPERATURE = 0.2
RAG_SUMMARY_MAX_TOKENS = 1500
RAG_SUMMARY_TOP_P = 0.9

ANALYSIS_TEMPERATURE = 0.2
ANALYSIS_MAX_TOKENS = 2500
ANALYSIS_TOP_P = 0.9
